# docker-compose.yml

version: '3.8'

services:
  fe:
    image: shepherd/fe
    build: ./fe
    ports:
      - 8080:80
  be:
    image: shepherd/be
    build: ./be
    ports:
      - 8081:80


  
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:13-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=fastapi_traefik
  #     - POSTGRES_PASSWORD=fastapi_traefik
  #     - POSTGRES_DB=fastapi_traefik

# volumes:
#   postgres_data: